/**
 * Copyright 2026 Gilang Albathin Nurhabibi <https://github.com/athron98>
 *
 * Author: Gilang Albathin Nurhabibi <https://github.com/athron98>
 *
 * SPDX-License-Identifier: MIT
 *
 * Licensed under the MIT License. See the LICENSE file at the repository root.
 *
 * Plugin contracts, mirrored from `@hamolus/plugin-console-contracts`.
 *
 * The console keeps its own copy on purpose. A console generated by
 * `hamolus add console` has no plugin dependency at all, so the host must be
 * able to describe a plugin without depending on the plugin packages. The
 * contracts package exists for the *other* direction — a plugin imports it to
 * learn the shapes it is handed — and the two files are kept in sync by the same
 * field names. If you change a field here, change it there too.
 *
 * The host writes this shape into `console.config.ts`, where
 * `@hamolus/types`' `consolePluginSchema` validates it field by field. This file is
 * what the console renders; the schema is what the host is checked against.
 */

import type { Component } from 'solid-js'

/**
 * One entry read from a plugin's KV namespace (a `plugin:{land}:{plugin}:{key}`
 * value). `key` is the part past the plugin's prefix, so plugins work with
 * bare keys like `item:a1b2c3` or `board`.
 */
export interface PluginKvEntry {
  key: string
  value: unknown
}

/** The thin KV surface the console hands to every plugin page. */
export interface KvClient {
  /** List every stored entry under the plugin's prefix. */
  list(): Promise<PluginKvEntry[]>
  /** Read one entry; returns `null` when no such key exists. */
  get<T = unknown>(key: string): Promise<T | null>
  /** Write one entry. Values are persisted as JSON. */
  set(key: string, value: unknown): Promise<void>
  /** Delete one entry. */
  del(key: string): Promise<void>
}

/** Permission bits derived for the signed-in user. */
export interface PluginPermissions {
  /** `settings.write` — plugin data may be created/updated/deleted. */
  canWrite: boolean
}

/** A self-contained console plugin, shipped from a separate workspace package. */
export interface ConsolePlugin {
  /** snake_case plugin id, also the KV prefix segment. */
  id: string
  name: string
  description: string
  icon?: string
  component: Component<PluginPageProps>
}

/** Props every plugin page receives. */
export interface PluginPageProps {
  plugin: ConsolePlugin
  kv: KvClient
  permissions: PluginPermissions
}
